import {
  ContentStatus,
  DATABASE_TABLES,
  EXPERT_STATUSES,
  PageType,
  SubscriberStatus,
  UserRole,
  UserStatus,
} from "./constants";

export type ColumnType =
  | "uuid"
  | "text"
  | "numeric"
  | "timestamp"
  | "jsonb"
  | "text[]"
  | "boolean"
  | "enum";

export type SchemaColumn = {
  name: string;
  type: ColumnType;
  nullable?: boolean;
  primaryKey?: boolean;
  references?: {
    table: string;
    column: string;
    onDelete?: "cascade" | "set null" | "restrict";
  };
  default?: string;
  enumValues?: readonly string[];
  indexed?: boolean;
  unique?: boolean;
};

export type TableSchema = {
  table: string;
  description: string;
  columns: SchemaColumn[];
};

export const databaseSchema: TableSchema[] = [
  {
    table: DATABASE_TABLES.categories,
    description: "SEO category pages and product/blog grouping.",
    columns: [
      { name: "id", type: "uuid", primaryKey: true, default: "gen_random_uuid()" },
      { name: "name", type: "text" },
      { name: "slug", type: "text", unique: true, indexed: true },
      { name: "description", type: "text", nullable: true },
      { name: "image", type: "text", nullable: true },
      { name: "seo_title", type: "text", nullable: true },
      { name: "seo_description", type: "text", nullable: true },
      { name: "created_at", type: "timestamp", default: "now()" },
      { name: "updated_at", type: "timestamp", default: "now()" },
    ],
  },
  {
    table: DATABASE_TABLES.products,
    description: "Affiliate supplement product detail pages.",
    columns: [
      { name: "id", type: "uuid", primaryKey: true, default: "gen_random_uuid()" },
      {
        name: "category_id",
        type: "uuid",
        references: { table: DATABASE_TABLES.categories, column: "id", onDelete: "restrict" },
        indexed: true,
      },
      {
        name: "author_id",
        type: "uuid",
        nullable: true,
        references: { table: DATABASE_TABLES.authors, column: "id", onDelete: "set null" },
        indexed: true,
      },
      {
        name: "reviewer_id",
        type: "uuid",
        nullable: true,
        references: { table: DATABASE_TABLES.reviewers, column: "id", onDelete: "set null" },
        indexed: true,
      },
      { name: "name", type: "text" },
      { name: "slug", type: "text", unique: true, indexed: true },
      { name: "short_description", type: "text", nullable: true },
      { name: "full_description", type: "text", nullable: true },
      { name: "image", type: "text", nullable: true },
      { name: "gallery", type: "text[]", default: "'{}'" },
      { name: "rating", type: "numeric", nullable: true },
      { name: "affiliate_url", type: "text", nullable: true },
      { name: "pros", type: "text[]", default: "'{}'" },
      { name: "cons", type: "text[]", default: "'{}'" },
      { name: "ingredients", type: "jsonb", default: "'[]'" },
      { name: "faq", type: "jsonb", default: "'[]'" },
      {
        name: "status",
        type: "enum",
        enumValues: Object.values(ContentStatus),
        default: ContentStatus.Draft,
        indexed: true,
      },
      { name: "seo_title", type: "text", nullable: true },
      { name: "seo_description", type: "text", nullable: true },
      { name: "created_at", type: "timestamp", default: "now()" },
      { name: "updated_at", type: "timestamp", default: "now()" },
    ],
  },
  {
    table: DATABASE_TABLES.blogs,
    description: "SEO editorial articles and supplement guides.",
    columns: [
      { name: "id", type: "uuid", primaryKey: true, default: "gen_random_uuid()" },
      {
        name: "category_id",
        type: "uuid",
        nullable: true,
        references: { table: DATABASE_TABLES.categories, column: "id", onDelete: "set null" },
        indexed: true,
      },
      {
        name: "author_id",
        type: "uuid",
        nullable: true,
        references: { table: DATABASE_TABLES.authors, column: "id", onDelete: "set null" },
        indexed: true,
      },
      {
        name: "reviewer_id",
        type: "uuid",
        nullable: true,
        references: { table: DATABASE_TABLES.reviewers, column: "id", onDelete: "set null" },
        indexed: true,
      },
      { name: "title", type: "text" },
      { name: "slug", type: "text", unique: true, indexed: true },
      { name: "excerpt", type: "text", nullable: true },
      { name: "content", type: "jsonb", default: "'{}'" },
      { name: "featured_image", type: "text", nullable: true },
      { name: "reading_time", type: "text", nullable: true },
      {
        name: "status",
        type: "enum",
        enumValues: Object.values(ContentStatus),
        default: ContentStatus.Draft,
        indexed: true,
      },
      { name: "seo_title", type: "text", nullable: true },
      { name: "seo_description", type: "text", nullable: true },
      { name: "published_at", type: "timestamp", nullable: true },
      { name: "created_at", type: "timestamp", default: "now()" },
      { name: "updated_at", type: "timestamp", default: "now()" },
    ],
  },
  {
    table: DATABASE_TABLES.authors,
    description: "Editorial author profiles.",
    columns: [
      { name: "id", type: "uuid", primaryKey: true, default: "gen_random_uuid()" },
      { name: "name", type: "text" },
      { name: "slug", type: "text", unique: true, indexed: true },
      { name: "photo_url", type: "text", nullable: true },
      { name: "designation", type: "text", nullable: true },
      { name: "qualification", type: "text", nullable: true },
      { name: "experience_years", type: "numeric", nullable: true },
      { name: "bio", type: "text", nullable: true },
      { name: "linkedin_url", type: "text", nullable: true },
      { name: "website_url", type: "text", nullable: true },
      { name: "email", type: "text", nullable: true, indexed: true },
      { name: "is_active", type: "boolean", default: "true", indexed: true },
      { name: "created_at", type: "timestamp", default: "now()" },
      { name: "updated_at", type: "timestamp", default: "now()" },
    ],
  },
  {
    table: DATABASE_TABLES.reviewers,
    description: "Medical reviewer and expert reviewer profiles.",
    columns: [
      { name: "id", type: "uuid", primaryKey: true, default: "gen_random_uuid()" },
      { name: "name", type: "text" },
      { name: "slug", type: "text", unique: true, indexed: true },
      { name: "photo_url", type: "text", nullable: true },
      { name: "designation", type: "text", nullable: true },
      { name: "qualification", type: "text", nullable: true },
      { name: "experience_years", type: "numeric", nullable: true },
      { name: "bio", type: "text", nullable: true },
      { name: "linkedin_url", type: "text", nullable: true },
      { name: "website_url", type: "text", nullable: true },
      { name: "email", type: "text", nullable: true, indexed: true },
      { name: "is_active", type: "boolean", default: "true", indexed: true },
      { name: "created_at", type: "timestamp", default: "now()" },
      { name: "updated_at", type: "timestamp", default: "now()" },
    ],
  },
  {
    table: DATABASE_TABLES.experts,
    description: "Public-facing wellness expert profiles used for advisory board, EEAT pages, and ask-expert workflows.",
    columns: [
      { name: "id", type: "uuid", primaryKey: true, default: "gen_random_uuid()" },
      { name: "name", type: "text" },
      { name: "slug", type: "text", unique: true, indexed: true },
      { name: "profile_image", type: "text", nullable: true },
      { name: "designation", type: "text", nullable: true },
      { name: "short_bio", type: "text", nullable: true },
      { name: "full_bio", type: "text", nullable: true },
      { name: "editorial_contribution", type: "text", nullable: true },
      { name: "experience_years", type: "numeric", nullable: true },
      { name: "linkedin_url", type: "text", nullable: true },
      { name: "website_url", type: "text", nullable: true },
      { name: "email", type: "text", nullable: true, indexed: true },
      { name: "expertise_tags", type: "text[]", default: "'{}'" },
      {
        name: "status",
        type: "enum",
        enumValues: EXPERT_STATUSES,
        default: "'active'",
        indexed: true,
      },
      { name: "display_order", type: "numeric", default: "0", indexed: true },
      { name: "featured_on_homepage", type: "boolean", default: "false", indexed: true },
      { name: "seo_title", type: "text", nullable: true },
      { name: "seo_description", type: "text", nullable: true },
      { name: "meta_image", type: "text", nullable: true },
      {
        name: "linked_author_id",
        type: "uuid",
        nullable: true,
        references: { table: DATABASE_TABLES.authors, column: "id", onDelete: "set null" },
        indexed: true,
      },
      {
        name: "linked_reviewer_id",
        type: "uuid",
        nullable: true,
        references: { table: DATABASE_TABLES.reviewers, column: "id", onDelete: "set null" },
        indexed: true,
      },
      { name: "created_at", type: "timestamp", default: "now()" },
      { name: "updated_at", type: "timestamp", default: "now()" },
    ],
  },
  {
    table: DATABASE_TABLES.users,
    description: "Admin, editor, and user accounts.",
    columns: [
      { name: "id", type: "uuid", primaryKey: true, default: "gen_random_uuid()" },
      { name: "full_name", type: "text", nullable: true },
      { name: "email", type: "text", unique: true, indexed: true },
      {
        name: "role",
        type: "enum",
        enumValues: Object.values(UserRole),
        default: UserRole.User,
        indexed: true,
      },
      { name: "avatar", type: "text", nullable: true },
      {
        name: "status",
        type: "enum",
        enumValues: Object.values(UserStatus),
        default: UserStatus.Pending,
        indexed: true,
      },
      { name: "created_at", type: "timestamp", default: "now()" },
    ],
  },
  {
    table: DATABASE_TABLES.seo,
    description: "Centralized metadata and structured data.",
    columns: [
      { name: "id", type: "uuid", primaryKey: true, default: "gen_random_uuid()" },
      { name: "page_type", type: "enum", enumValues: Object.values(PageType), indexed: true },
      { name: "page_slug", type: "text", indexed: true },
      { name: "meta_title", type: "text" },
      { name: "meta_description", type: "text" },
      { name: "canonical_url", type: "text", nullable: true },
      { name: "schema_json", type: "jsonb", default: "'{}'" },
      { name: "updated_at", type: "timestamp", default: "now()" },
    ],
  },
  {
    table: DATABASE_TABLES.ingredients,
    description: "Ingredient library reference pages and SEO authority content.",
    columns: [
      { name: "id", type: "uuid", primaryKey: true, default: "gen_random_uuid()" },
      { name: "name", type: "text" },
      { name: "slug", type: "text", unique: true, indexed: true },
      {
        name: "author_id",
        type: "uuid",
        nullable: true,
        references: { table: DATABASE_TABLES.authors, column: "id", onDelete: "set null" },
        indexed: true,
      },
      {
        name: "reviewer_id",
        type: "uuid",
        nullable: true,
        references: { table: DATABASE_TABLES.reviewers, column: "id", onDelete: "set null" },
        indexed: true,
      },
      { name: "scientific_name", type: "text", nullable: true },
      { name: "ingredient_category", type: "text", nullable: true },
      { name: "short_description", type: "text", nullable: true },
      { name: "full_description", type: "text", nullable: true },
      { name: "image_url", type: "text", nullable: true },
      {
        name: "status",
        type: "enum",
        enumValues: Object.values(ContentStatus),
        default: ContentStatus.Draft,
        indexed: true,
      },
      { name: "rating", type: "numeric", nullable: true },
      { name: "evidence_level", type: "text", nullable: true },
      { name: "origin_country", type: "text", nullable: true },
      { name: "part_used", type: "text", nullable: true },
      { name: "ingredient_form", type: "text", nullable: true },
      { name: "taste_profile", type: "text", nullable: true },
      { name: "typical_dose", type: "text", nullable: true },
      { name: "best_for", type: "text", nullable: true },
      { name: "safety_level", type: "text", nullable: true },
      { name: "overview_content", type: "text", nullable: true },
      { name: "how_it_works_content", type: "text", nullable: true },
      { name: "interesting_fact", type: "text", nullable: true },
      { name: "benefits", type: "text[]", default: "'{}'" },
      { name: "side_effects", type: "text[]", default: "'{}'" },
      { name: "dosage", type: "text", nullable: true },
      { name: "scientific_notes", type: "text", nullable: true },
      { name: "benefits_json", type: "jsonb", default: "'[]'" },
      { name: "side_effects_json", type: "jsonb", default: "'[]'" },
      { name: "drug_interactions_json", type: "jsonb", default: "'[]'" },
      { name: "who_should_avoid_json", type: "jsonb", default: "'[]'" },
      { name: "faq_json", type: "jsonb", default: "'[]'" },
      { name: "related_ingredients_json", type: "jsonb", default: "'[]'" },
      { name: "featured_image", type: "text", nullable: true },
      { name: "meta_title", type: "text", nullable: true },
      { name: "meta_description", type: "text", nullable: true },
      { name: "seo_title", type: "text", nullable: true },
      { name: "seo_description", type: "text", nullable: true },
      { name: "is_featured", type: "boolean", default: "false", indexed: true },
      { name: "created_at", type: "timestamp", default: "now()" },
      { name: "updated_at", type: "timestamp", default: "now()" },
    ],
  },
  {
    table: DATABASE_TABLES.productIngredients,
    description: "Many-to-many product and ingredient relationships.",
    columns: [
      { name: "id", type: "uuid", primaryKey: true, default: "gen_random_uuid()" },
      {
        name: "product_id",
        type: "uuid",
        references: { table: DATABASE_TABLES.products, column: "id", onDelete: "cascade" },
        indexed: true,
      },
      {
        name: "ingredient_id",
        type: "uuid",
        references: { table: DATABASE_TABLES.ingredients, column: "id", onDelete: "cascade" },
        indexed: true,
      },
      { name: "created_at", type: "timestamp", default: "now()" },
    ],
  },
  {
    table: DATABASE_TABLES.newsletterSubscribers,
    description: "Newsletter opt-ins and subscription status.",
    columns: [
      { name: "id", type: "uuid", primaryKey: true, default: "gen_random_uuid()" },
      { name: "email", type: "text", unique: true, indexed: true },
      {
        name: "status",
        type: "enum",
        enumValues: Object.values(SubscriberStatus),
        default: SubscriberStatus.Pending,
        indexed: true,
      },
      { name: "created_at", type: "timestamp", default: "now()" },
    ],
  },
  {
    table: DATABASE_TABLES.expertQueries,
    description: "Ask-expert questions submitted from product pages and the public ask-expert form.",
    columns: [
      { name: "id", type: "uuid", primaryKey: true, default: "gen_random_uuid()" },
      { name: "name", type: "text", indexed: true },
      { name: "email", type: "text", indexed: true },
      { name: "category", type: "text", nullable: true, indexed: true },
      {
        name: "expert_id",
        type: "uuid",
        nullable: true,
        references: { table: DATABASE_TABLES.experts, column: "id", onDelete: "set null" },
        indexed: true,
      },
      { name: "product_name", type: "text", nullable: true, indexed: true },
      { name: "product_url", type: "text", nullable: true },
      { name: "question_type", type: "text", indexed: true },
      { name: "message", type: "text" },
      { name: "status", type: "text", default: "'new'", indexed: true },
      { name: "source_page", type: "text", nullable: true },
      { name: "created_at", type: "timestamp", default: "now()", indexed: true },
      { name: "updated_at", type: "timestamp", nullable: true },
      { name: "resolved_at", type: "timestamp", nullable: true },
    ],
  },
  {
    table: DATABASE_TABLES.affiliateClicks,
    description: "Affiliate click analytics.",
    columns: [
      { name: "id", type: "uuid", primaryKey: true, default: "gen_random_uuid()" },
      {
        name: "product_id",
        type: "uuid",
        references: { table: DATABASE_TABLES.products, column: "id", onDelete: "cascade" },
        indexed: true,
      },
      { name: "clicked_at", type: "timestamp", default: "now()", indexed: true },
      { name: "source_page", type: "text", nullable: true },
      { name: "country", type: "text", nullable: true },
      { name: "device", type: "text", nullable: true },
      { name: "user_agent", type: "text", nullable: true },
      { name: "ip_hash", type: "text", nullable: true },
      { name: "referrer", type: "text", nullable: true },
    ],
  },
  {
    table: DATABASE_TABLES.mediaLibrary,
    description: "Central media library assets and SEO image metadata.",
    columns: [
      { name: "id", type: "uuid", primaryKey: true, default: "gen_random_uuid()" },
      { name: "file_name", type: "text", unique: true, indexed: true },
      { name: "file_url", type: "text", unique: true, indexed: true },
      { name: "title", type: "text", indexed: true },
      { name: "alt_text", type: "text", nullable: true },
      { name: "caption", type: "text", nullable: true },
      { name: "description", type: "text", nullable: true },
      { name: "slug", type: "text", indexed: true },
      { name: "tags", type: "text[]", default: "'{}'" },
      { name: "width", type: "numeric", nullable: true },
      { name: "height", type: "numeric", nullable: true },
      { name: "file_size", type: "numeric", nullable: true },
      { name: "mime_type", type: "text", nullable: true },
      { name: "created_at", type: "timestamp", default: "now()" },
      { name: "updated_at", type: "timestamp", default: "now()" },
    ],
  },
  {
    table: DATABASE_TABLES.siteSettings,
    description: "Global site branding and content settings.",
    columns: [
      { name: "id", type: "uuid", primaryKey: true, default: "gen_random_uuid()" },
      { name: "site_name", type: "text" },
      { name: "logo", type: "text", nullable: true },
      { name: "favicon", type: "text", nullable: true },
      { name: "social_links", type: "jsonb", default: "'{}'" },
      { name: "footer_content", type: "jsonb", default: "'{}'" },
      { name: "contact_email", type: "text", nullable: true },
      { name: "updated_at", type: "timestamp", default: "now()" },
    ],
  },
];
